version: '3'

includes:
  tf:
    taskfile: ./terraform/Taskfile.yml
    dir: ./terraform

  authz:
    taskfile: ./src/authorizer/Taskfile.yml
    dir: ./src/authorizer

tasks:
  deploy-terraform:
    dir: ./terraform
    cmds:
      - terraform init
      - terraform apply

  tearup:
    desc: This destroy all related terraform resources with this dir, be sure to have the correct AWS credentials configured
    dir: ./terraform
    cmds:
      - terraform destroy --auto-approve

  setup:
    desc: This will create the related terraform resources with this dir, be sure to have the correct AWS credentials configured
    cmds:
      - task: authz:build
      - task: deploy-terraform
      - task: tf:create-cognito-user

  test-ws-cognito:
    vars:
      API_GW_URL:
        sh: task tf:get-http-url
      JWT:
        sh: task tf:get-cognito-user-jwt
    cmds:
      - |
        curl --include --no-buffer \
        -H "Connection: Upgrade" \
        -H "Upgrade: websocket" \
        -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
        -H "Sec-WebSocket-Version: 13" \
        -H 'Auth:{{.JWT}}' \
        --max-time 2.0 \
        {{.API_GW_URL}}

  start-ws-cognito:
    vars:
      API_GW_URL:
        sh: task tf:get-ws-url
      JWT:
        sh: task tf:get-cognito-user-jwt
    cmds:
      - |
        wscat -c {{.API_GW_URL}}  -H "Auth:{{.JWT}}"

  test-ws-selfsigned:
    vars:
      API_GW_URL:
        sh: task tf:get-apigw-url
      JWT:
        sh: task authz:generate-jwt
    cmds:
      - |
        curl --include --no-buffer \
        -H "Connection: Upgrade" \
        -H "Upgrade: websocket" \
        -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
        -H "Sec-WebSocket-Version: 13" \
        -H 'Auth:{{.JWT}}' \
        --max-time 2.0 \
        {{.API_GW_URL}}

  start-ws-selfsigned:
    vars:
      API_GW_URL:
        sh: task tf:get-ws-url
      JWT:
        sh: task authz:generate-jwt
    cmds:
      - |
        wscat -c {{.API_GW_URL}}  -H "Auth:{{.JWT}}"

  docs:
    desc: Start structurizr server to display docs
    cmds:
      - docker run -it --rm -p 8080:8080 -v $(pwd):/usr/local/structurizr structurizr/lite
