version: '3'

tasks:
  test:
    cmds:
      - go test -v ./... -coverprofile=coverage.out
    sources:
      - ./**/*.go
    generates:
      - ./coverage.out

  build:
    deps: [test]
    dir: ./cmd/lambda/
    cmds:
      - mkdir -p bin
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/authorizer
    sources:
      - ./**/*.go
    generates:
      - ./bin/authorizer

  coverage:
    deps: [test]
    cmds:
      - go tool cover -html=coverage.out 

  generate-keypair:
    dir: ./cmd/jwk_creator/
    cmds:
      - |
        go run . {{.CLI_ARGS}}

  generate-jwt:
    dir: ./cmd/jwt_client
    cmds:
      - go run . myGroup
