version: '3'

tasks:
  deploy-terraform:
    dir: ./terraform
    cmds:
      - terraform init
      - terraform apply

  create-cognito-user:
    desc: This will create a new user in the cognito pool deployed by the terraform it will create a new password for it, be sure to have the correct AWS credentials configured
    dir: ./terraform
    vars:
      USERNAME: '{{default "a_user" .USERNAME}}'
      OLD_PASSWORD: '{{default "abc1-Dand" .OLD_PASSWORD}}'
      NEW_PASSWORD: '{{default "zpwe2-Dand" .NEW_PASSWORD}}'
    cmds:
      - |
        COG_CLIENT_ID=$(terraform output -json | jq -j '.client_id.value')
        COG_POOL_ID=$(terraform output -json | jq -j '.user_pool_id.value')
        aws cognito-idp admin-create-user --user-pool-id ${COG_POOL_ID} --username {{.USERNAME}} --temporary-password={{.OLD_PASSWORD}} > /dev/null
        NEW_USER_SESSION=$(aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --client-id ${COG_CLIENT_ID} --auth-parameters USERNAME={{.USERNAME}},PASSWORD={{.OLD_PASSWORD}} --output text --query 'Session')
        aws cognito-idp respond-to-auth-challenge --client-id ${COG_CLIENT_ID} --challenge-name NEW_PASSWORD_REQUIRED --session ${NEW_USER_SESSION} --challenge-responses USERNAME={{.USERNAME}},NEW_PASSWORD={{.NEW_PASSWORD}} >/dev/null

  get-cognito-user-jwt:
    desc: This will get a new cognito JWT using user credentials, be sure to have the correct AWS credentials configured
    dir: ./terraform
    vars:
      USERNAME: '{{default "a_user" .USERNAME}}'
      PASSWORD: '{{default "zpwe2-Dand" .NEW_PASSWORD}}'
    cmds:
      - |
        COG_CLIENT_ID=$(terraform output -json | jq -j '.client_id.value')
        aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --client-id ${COG_CLIENT_ID} --auth-parameters USERNAME={{.USERNAME}},PASSWORD={{.PASSWORD}} --output text --query 'AuthenticationResult.IdToken'

  tearup:
    desc: This destroy all related terraform resources with this dir, be sure to have the correct AWS credentials configured
    dir: ./terraform
    cmds:
      - terraform destroy --auto-approve

  setup:
    desc: This will create the related terraform resources with this dir, be sure to have the correct AWS credentials configured
    cmds:
      - task: deploy-terraform
      - task: create-cognito-user

  get-apigw-url:
    dir: ./terraform
    cmds:
      - terraform output -json | jq -j '.url.value'

  docs:
    desc: Start structurizr server to display docs
    cmds:
      - docker run -it --rm -p 8080:8080 -v $(pwd):/usr/local/structurizr structurizr/lite
